### ISSUE TITLE
Plugin crash after confirming permissions

### ISSUE THREAD

**Issue by philipjohnbarlow** [enricofer/gdrive_provider#1]
Hi, 

Just had a quick go at setting up your plugin and I am getting the following error message once account permission have been accepted.

![image](https://cloud.githubusercontent.com/assets/14541141/25737840/ca57e012-3171-11e7-8524-ea563d5ae87b.png)

Phil

**Comment by enricofer** [comment]
Hi Phil,
this is a well known [httplib2 issue](http://stackoverflow.com/questions/15696526/ssl-throwing-error-185090050-while-authentication-via-oauth) related to certificates files location or read rights.
I solved this putting a new cacerts.txt file (C:\Users\philipb\.qgis2\python\plugins\gdrive_provider\credentials\cacerts.txt in your system).
I ask you:
1) to check if this file exists and is readable.
2) download manually a new cacerts.txt For example [this](https://raw.githubusercontent.com/bryanhelmig/httplib2/master/httplib2/cacerts.txt) or [this](https://raw.githubusercontent.com/GoogleCloudPlatform/billing-export-python/master/httplib2/cacerts.txt)
3) try to replace old file (keep it somewhere) with the new downloaded one and retry connection
4) or try to put the downloaded file in a location readable for actual QGIS user and modify line 133 of services.py file (C:\Users\philipb\.qgis2\python\plugins\gdrive_provider\services.py in your system)
`self.httpConnection = httplib2.Http(proxy_info = proxyConf, ca_certs=os.path.join(self.credential_dir,'cacerts.txt'))`
giving the explicit location of downloaded cacerts file, for example:
`self.httpConnection = httplib2.Http(proxy_info = proxyConf, ca_certs='C:\\Users\\philipb\\Download\\cacerts.txt')`
note that the path has double backslash to avoid python formatting mismatch
restart QGIS and reconnect
5) or try to simply erase ca_cert parameter from row 133:
`self.httpConnection = httplib2.Http(proxy_info = proxyConf)`
restart QGIS and reconnect

Let me know if it goes.

Regards, Enrico.

**Comment by philipjohnbarlow** [comment]
Hi Enrico,

No joy with any of the methods suggested above, still getting the same error.  I wonder if it is down security settings on my workstation (I am at work).

Phil

**Comment by enricofer** [comment]
Did you install QGIS as admin and plugin as other user or viceversa?
I'm not thinking to system wide settings but to python environment settings
Could you try to manually download [httplib2 ](https://github.com/httplib2/httplib2) and put the httlib2 directory under python2 in extlib directory in your plugin? 
... after that you have to reload plugin and retry from start.

**Comment by All4Gis** [comment]
I can't reproduce it.
What QGIS version you have?
httplib2 version?
Yo can try load this in your QGIS python console?change the ca_certs with your path

> import httplib2
> import requests
> import os
> 
> cert_path='C://Users//fran//.qgis2//python//plugins//gdrive_provider//credentials//cacerts.txt'
> httplib2.Http(ca_certs=cert_path)

And try this too:

> print requests.get('https://www.google.com/', verify=cert_path).text

Do you have a proxy in your company?Can you try it on another pc?

**Comment by philipjohnbarlow** [comment]
Apologies for not getting back sooner on this, yes there is a proxy at my work place.  I'll try the plugin at home instead.

**Comment by enricofer** [comment]
Hi Francisco, as I told you I would like to test GooGIS plugin with the
help of many concurrent users. Next Sunday 12 november and Monday 13
november I will meet many qgis user for a QGIS_IT hackfest
https://github.com/qgis-it/qgis-it.github.io/wiki/QHF-IT2 so I will retry
testing. I would like to involve you too if You like.
As soon as I will be able to schedule test I will advice you.

Regards.
Enrico

2017-06-29 11:00 GMT+02:00 philipjohnbarlow <notifications@github.com>:

**Comment by All4Gis** [comment]
Yes of course,You can count on me to testing
