### ISSUE TITLE
Compatibility with QGIS v3?

### ISSUE THREAD

**Issue by ghost** [enricofer/gdrive_provider#3]
Hi, this project looks very useful for archaeological data! Do you have any plans to update it for QGIS 3?

**Comment by enricofer** [comment]
Maybe in the next future. The plug-in is quite complex and the migration is not so easy.

**Comment by enricofer** [comment]
first running QGIS3 porting is now available on master. Could you test it?

**Comment by alpterlab** [comment]
Just can not figure out how to make i work....

>  from .gdrive_provider import Google_Drive_Provider
>               File "C:/OSGEO4~1/apps/qgis-dev/./python\qgis\utils.py", line 737, in _import
>               mod = _builtin_import(name, globals, locals, fromlist, level)
>               File "C:/Users/info/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gdrive_provider-master\gdrive_provider.py", line 45, in 
>               from .gdrive_layer import progressBar, GoogleDriveLayer
>               File "C:/OSGEO4~1/apps/qgis-dev/./python\qgis\utils.py", line 737, in _import
>               mod = _builtin_import(name, globals, locals, fromlist, level)
>               File "C:/Users/info/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gdrive_provider-master\gdrive_layer.py", line 69, in 
>               from .services import pack, unpack, google_authorization, service_drive, service_spreadsheet
>               File "C:/OSGEO4~1/apps/qgis-dev/./python\qgis\utils.py", line 737, in _import
>               mod = _builtin_import(name, globals, locals, fromlist, level)
>               File "C:/Users/info/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gdrive_provider-master\services.py", line 62, in 
>               from oauth2client import client, GOOGLE_TOKEN_URI
>               File "C:/OSGEO4~1/apps/qgis-dev/./python\qgis\utils.py", line 737, in _import
>               mod = _builtin_import(name, globals, locals, fromlist, level)
>               File "C:\Users\info\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\gdrive_provider-master\extlibs\oauth2client\client.py", line 41, in 
>               from gdrive_provider.extlibs.oauth2client import GOOGLE_REVOKE_URI
>               File "C:/OSGEO4~1/apps/qgis-dev/./python\qgis\utils.py", line 737, in _import
>               mod = _builtin_import(name, globals, locals, fromlist, level)
>               File "C:/Users/info/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gdrive_provider-master\gdrive_provider.py", line 44, in 
>               from .gdrive_provider_dialog import GoogleDriveProviderDialog, accountDialog, comboDialog, importFromIdDialog, internalBrowser, webMapDialog
>               File "C:/OSGEO4~1/apps/qgis-dev/./python\qgis\utils.py", line 737, in _import
>               mod = _builtin_import(name, globals, locals, fromlist, level)
>              ImportError: attempted relative import with no known parent package
>
