### ISSUE TITLE
Error to SYNC with Googlr Drive

### ISSUE THREAD

**Issue by bellanz80** [enricofer/gdrive_provider#5]
Hello, this plug is a great idea, it has enormous possibilities!
Today I did my first test.
I created a layer, gave it a style, uploaded it to google. I attached a colleague's email, to be able to read / write.
he could see the layer on the panel and load it. He was able to modify the layer, adding more polygons.
But now, if I give the command "SYNC with google Drive" it returns a python error, and it doesn't update.
I must delete the layer, and load it again from the panel, so that the modifications of the other user are loaded.

win 10 QGIS 3.12.2

ERROR:
2020-05-19T13:16:27     WARNING    Traceback (most recent call last):
              File "C:/Users/UV/AppData/Roaming/QGIS/QGIS3\profiles\4/python/plugins\gdrive_provider\gdrive_layer.py", line 305, in sync_with_google_drive
              self.update_from_subscription()
              File "C:/Users/UV/AppData/Roaming/QGIS/QGIS3\profiles\4/python/plugins\gdrive_provider\gdrive_layer.py", line 316, in update_from_subscription
              updates = self.service_sheet.get_line('COLUMNS','A', sheet=self.client_id)
              File "C:/Users/UV/AppData/Roaming/QGIS/QGIS3\profiles\4/python/plugins\gdrive_provider\services.py", line 821, in get_line
              valueRenderOption='UNFORMATTED_VALUE').execute()
              File "C:\Users\UV\AppData\Roaming\QGIS\QGIS3\profiles\4\python\plugins\gdrive_provider\extlibs\googleapiclient\_helpers.py", line 130, in positional_wrapper
              return wrapped(*args, **kwargs)
              File "C:\Users\UV\AppData\Roaming\QGIS\QGIS3\profiles\4\python\plugins\gdrive_provider\extlibs\googleapiclient\http.py", line 851, in execute
              raise HttpError(resp, content, uri=self.uri)
             googleapiclient.errors.HttpError:

**Comment by enricofer** [comment]
Something happened but I can't figure what. Unfortunately the exception trace is not enough and you should help me providing the exact operating steps that bring to the issue (data model, type of editing, operating context, etc...) 
Anyway could you start sharing with me the faulty layer? enricofer@gmail.com

**Comment by bellanz80** [comment]
Sure, I just attached it with write permission.
the layer is called prueba_GOOGIS
Thank you!

**Comment by enricofer** [comment]
No luck. I can't see it. Could you share it with me from drive.google.com ?

**Comment by bellanz80** [comment]
Yes, check!

**Comment by bellanz80** [comment]
I keep inserting your email in the panel, and click "update permission" but when I open the plug panel, the inserted mail continues to disappear.

**Comment by enricofer** [comment]
No problem here. I opened, modified and save it.
Now I opened it and I'm editing the F feature so if you open now you should not be able to modify that feature

**Comment by enricofer** [comment]
![Screenshot 2020-05-19 22 14 39](https://user-images.githubusercontent.com/7544963/82374037-c9967a80-9a1e-11ea-9d58-71a174317ad2.png)

**Comment by bellanz80** [comment]
thanks, the preview in the panel was not updated, but when loading the layer, effectively there was the letter F, and I confirm that I cannot modify it or delete it. I suppose only the owner of the mod, can act on that element.

Now I have 2 other questions:
1) how does saving the style work?
That is to say, it seems to me that every time I change it, it is automatically saved in Google Drive.

2) what is the function of the "sync with google drive" menu? Is it useful to be working with more synchronous people, I can do a kind of RELOAD of the layer, and see the changes made by other users remotely?

Many thanks

Luca

**Comment by enricofer** [comment]
1. the layer style is saved along with layer in a dedicated hidden data space, and is syncronized at every props edit. All layer users view the data in the same way
2. It is needed to force syncronization between local layer and google sheet table, exchanging local and remote edits. The syncronization otherwise is performed only when removing the layer or when saving edits (in this case only local to remote). This function is useful to get current edits made by concurrent users. In the normal use it is not necessary to manually sync the local table and you can simply rely on automatic sync, saving bandwidth and API usage.

**Comment by bellanz80** [comment]
Many thank's!
